"""empty message

Revision ID: 1941166747d0
Revises: afce7e599fbe
Create Date: 2019-05-15 11:50:15.972700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1941166747d0'
down_revision = 'afce7e599fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_broker', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_broker')
    # ### end Alembic commands ###
