"""empty message

Revision ID: 44fe3817946f
Revises: a3ec0c165a30
Create Date: 2019-05-16 18:41:09.805573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44fe3817946f'
down_revision = 'a3ec0c165a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'house', ['room_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'house', type_='unique')
    # ### end Alembic commands ###
