"""empty message

Revision ID: 6ad2d77c9221
Revises: 1941166747d0
Create Date: 2019-05-15 16:51:21.851370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad2d77c9221'
down_revision = '1941166747d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house', sa.Column('broker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'house', 'user', ['broker_id'], ['id'])
    op.add_column('user', sa.Column('phone', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_constraint(None, 'house', type_='foreignkey')
    op.drop_column('house', 'broker_id')
    # ### end Alembic commands ###
