"""empty message

Revision ID: daa12e91b319
Revises: 49fa13719bd3
Create Date: 2019-05-16 18:23:24.902685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa12e91b319'
down_revision = '49fa13719bd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house', sa.Column('room_id', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'message', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'user_id')
    op.drop_column('house', 'room_id')
    # ### end Alembic commands ###
